name: Test ProblemMatchers

on:
    pull_request:

jobs:
    test_matchers:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  coverage: xdebug
            - name: Setup problem matchers for PHPUnit
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
            - name: Validate composer.json and composer.lock
              run: composer validate --strict
            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: ${{ runner.os }}-composer-
            - name: Install Composer dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader
            - name: Run Tests
              run: |
                php vendor/bin/phpunit --coverage-clover coverage.xml --configuration phpunit.xml
            - name: Outout dir
              run: ls -la
            - name: Generate code coverage image
              id: do-stuff # This is referred to below when fetching output
              run: php generate-code-coverage-image.php
            - name: Add comment to PR
              env:
                URL: ${{ github.event.issue.comments_url }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                curl \
                  -X POST \
                  $URL \
                  -H "Content-Type: application/json" \
                  -H "Authorization: token $GITHUB_TOKEN" \
                  --data '{ "body": "abc" }'